const Menu=[
    {
        id:1,
        image:"images/ln1.jpg",
        name:"Biriani",
        category:"lunch",
        price:"10$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:2,
        image:"images/ln2.jpg",
        name:"Kacci",
        category:"lunch",
        price:"12$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:3,
        image:"images/ln3.jpg",
        name:"Beff Rice",
        category:"lunch",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:4,
        image:"images/brk1.jpg",
        name:"Beff Rice",
        category:"Breakfast",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:5,
        image:"images/brk2.jpg",
        name:"Beff Rice",
        category:"Breakfast",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:6,
        image:"images/brk3.jpg",
        name:"Beff Rice",
        category:"Breakfast",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:7,
        image:"images/din1.jpg",
        name:"Beff Rice",
        category:"Dinner",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:8,
        image:"images/din2.jpg",
        name:"Beff Rice",
        category:"Dinner",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:9,
        image:"images/din3.jpg",
        name:"Beff Rice",
        category:"Dinner",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:10,
        image:"images/ev1.jpg",
        name:"Beff Rice",
        category:"Eveinig",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:11,
        image:"images/ev2.jpg",
        name:"Beff Rice",
        category:"Eveinig",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:12,
        image:"images/ev3.jpg",
        name:"Beff Rice",
        category:"Eveinig",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
   
    {
        id:13,
        image:"images/ev3.jpg",
        name:"div",
        category:"div",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
    {
        id:14,
        image:"images/ev3.jpg",
        name:"khabar",
        category:"khabar",
        price:"8$",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita.",
    },
];
export default Menu;
